[workspace]
members = [
    "core",
    "compiler",
    "decompiler",
    "cli",
    "scc/cli",
    "scc/lib",
    "scc/lib-tests",
]
resolver = "2"

[workspace.package]
version = "0.5.27"
authors = ["jekky"]
edition = "2021"

[workspace.dependencies]
log = "0.4"
thiserror = "2"
anyhow = "1"
hashbrown = "0.15"
itertools = "0.14"
strum = { version = "0.27", features = ["derive"] }
enum-as-inner = "0.6"
modular-bitfield = "0.11"
byteorder = "1"
flexstr = "0.9"
crc32fast = "1"
flexi_logger = { version = "0.29", default-features = false }
hamt-sync = { git = "https://github.com/jac3km4/hamt-sync", rev = "v0.2.6" }
sequence_trie = { git = "https://github.com/jac3km4/rust_sequence_trie", rev = "a056b4c" }
peg = "0.8"
argh = "0.1"
walkdir = "2"
vmap = { version = "0.6", default-features = false }
rusty-hook = "0.11"

[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
let-underscore = "deny"
nonstandard-style = "deny"
rust-2018-compatibility = "deny"
rust-2018-idioms = "deny"
rust-2021-compatibility = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
match_same_arms = "deny"
semicolon_if_nothing_returned = "deny"
single_match_else = "deny"
redundant_closure_for_method_calls = "deny"
cloned_instead_of_copied = "deny"
redundant_else = "deny"
unnested_or_patterns = "deny"
unreadable_literal = "deny"
type_repetition_in_bounds = "deny"
equatable_if_let = "deny"
implicit_clone = "deny"
default_trait_access = "deny"
explicit_deref_methods = "deny"
explicit_iter_loop = "deny"
inefficient_to_string = "deny"
match_bool = "deny"

[workspace.metadata.release]
pre-release-commit-message = "chore: release {{version}}"
tag-prefix = ""
shared-version = true
publish = false

[profile.release]
lto = true
codegen-units = 1
