[args]
scriptsBlobPath = "{game_dir}\\r6\\cache\\modded\\final.redscripts"

[[tasks]]
command = "InvokeScc"
path = "{game_dir}\\r6\\scripts"
custom_bundle = "{game_dir}\\r6\\cache\\modded\\final.redscripts"
