on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      suffix:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    env:
      ARCHIVE_NAME: redscript-${{ github.ref_name }}-${{ inputs.suffix }}.zip
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ inputs.os }}
      - if: ${{ inputs.os == 'windows-latest' }}
        run: .\resources\package.ps1 -stagingDir "${{ runner.temp }}\redscript-staging" -archiveName "${{ env.ARCHIVE_NAME }}"
      - if: ${{ inputs.os != 'windows-latest' }}
        run: ./resources/package.sh "${{ runner.temp }}/redscript-staging" "${{ env.ARCHIVE_NAME }}"
      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          path: |
            target/release/redscript-cli.exe
            target/release/redscript-cli
            ${{ runner.temp }}/redscript-staging/${{ env.ARCHIVE_NAME }}
          name: artifact-${{ inputs.os }}
          if-no-files-found: error
