name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and upload a release artifact for ${{ matrix.os }}
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
        include:
          - os: windows-latest
            suffix: windows
          - os: macos-14
            suffix: macos
    with:
      os: ${{ matrix.os }}
      suffix: ${{ matrix.suffix }}

  publish:
    name: Release artifacts
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          FLAGS=(--generate-notes)
          ARTIFACTS=$(find ./artifacts -type f)

          if echo ${{ github.ref_name }} | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+-.+'; then
            FLAGS+=(--prerelease)
          fi

          gh release create ${{ github.ref_name }} ${FLAGS[@]} $ARTIFACTS
